NVIDIA/KAI-Scheduler

docs/quickstart/pods/gpu-pod.yaml

This is to add classic nvidia-smi to example gpu-pod 
```
$ kubectl get pod
NAME      READY   STATUS    RESTARTS   AGE
gpu-pod   1/1     Running   0          6s
$ kubectl logs gpu-pod
Tue Apr  1 21:39:23 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.86.15              Driver Version: 570.86.15      CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. | …
```

Add nvidia-smi to example gpu-pod

---

docs/batch/README.md

This update corrects the documentation for PyTorchJob in batch scheduling to reflect the fact that the kubeflow-training-operator-v1 is required, rather than the v2 version. The original instructions were misleading, as the v2 version does not support the necessary functionality for scheduling jobs as described. The updated doc now correctly points to the legacy v1 version of the operator, which is compatible with gang scheduling for PyTorch jobs.

docs: specify legacy v1 version of kubeflow-training-operator

---

docs/elastic/pytorch-elastic.yaml

- runai/queue is added
- fixed the typo in the yaml name

Docs hotfix: Update and rename pytorch-elasitc.yaml to pytorch-elastic.yaml

---

docs/priority/README.md

Was reading up on the priority docs and just noticed this spelling error.

Fix typo in priority docs

---

pkg/scheduler/actions/utils/job_order_by_queue.go

Created this as a test MR to see what the contribution process looks like. 
The PR moves a code block that is unnecessarily repeated under a for loop. There appears to be a bug in the `buildActiveJobOrderPriorityQueues` method. The code between lines 214-221 is incorrectly placed inside the outer for loop that iterates over `jobsOrder.ssn.Queues`. This means that for every queue, it's:
* Creating a new activeDepartments priority queue
* Rebuilding the entire department priority queue from scratch
* Pushing all departments into it
Looks inefficient.

Remove repeated active departments queue creation 

---

pkg/scheduler/actions/allocate/allocateElastic_test.go
pkg/scheduler/actions/allocate/allocateFractionalGpu_test.go
pkg/scheduler/actions/allocate/allocateGang_test.go
pkg/scheduler/actions/allocate/allocateGpuMemory_test.go
pkg/scheduler/actions/allocate/allocateMIG_test.go
pkg/scheduler/actions/allocate/allocate_test.go
pkg/scheduler/actions/consolidation/consolidation_test.go
pkg/scheduler/actions/integration_tests/integration_tests_utils/integration_tests_utils.go
pkg/scheduler/actions/preempt/preemptGang_test.go
pkg/scheduler/actions/preempt/preemptMIG_test.go
pkg/scheduler/actions/preempt/preempt_elastic_test.go
pkg/scheduler/actions/preempt/preempt_test.go
pkg/scheduler/actions/reclaim/reclaimDepartments_test.go
pkg/scheduler/actions/reclaim/reclaimGang_test.go
pkg/scheduler/actions/reclaim/reclaimMIG_test.go
pkg/scheduler/actions/reclaim/reclaim_elastic_test.go
pkg/scheduler/actions/reclaim/reclaim_test.go

Currently some tests are trying to read TestToplogyMetadata.Name which is empty for all tests, causing go test -v to return very non-descript test cases such as `integration_tests_utils.go:52: Running test number: 0, test name: ` Since .TestTopologyBasic.Name is set for all cases, this diff changes all log lines to that instead for now.
Now they output:
`reclaim_test.go:31: Running test number: 11, test name: 1 train job of 2 GPUs from queue0 running on node0 with deserved of 1, 2 pending jobs from queue1 - reclaim,`

Add/amend test logging to use .TestTopologyBasic.Name

---

CHANGELOG.md
pkg/env-tests/scheduler_test.go
pkg/env-tests/utils.go
pkg/scheduler/api/pod_info/pod_info.go
pkg/scheduler/api/pod_status/pod_status.go
pkg/scheduler/api/pod_status/pod_status_test.go
pkg/scheduler/api/podgroup_info/allocation_info.go
pkg/scheduler/api/podgroup_info/job_info.go
pkg/scheduler/api/podgroup_info/job_info_test.go
pkg/scheduler/cache/status_updater/default_status_updater.go
test/e2e/modules/resources/rd/pod_group/pod_group.go

See https://kubernetes.io/docs/concepts/scheduling-eviction/pod-scheduling-readiness/ & #63 
We want to respect k8s pod scheduling gates, which are used to delay pending pods from being considered for scheduling until other conditions in the cluster are met.
For podgroups, gated pods will not count towards "minMember". So, for example, a podgroup with minMember=4, 4 pending pods, with one of them being gated - will be considered not ready for scheduling. However, if the podgroup has enough ungated pods to satisfy minMember - it will schedule those pods. Additional pods will get scheduled as they become ungated.

Scheduling gates

---

cmd/binder/app/app.go

In order to handle scale better in clusters with very large number of pods where API calls that filter pods are very slow.

refactor(binder): add cache to the resource reservation client

---

pkg/podgrouper/podgrouper/plugins/kubeflow/pytorch/pytorch_grouper.go
pkg/podgrouper/podgrouper/plugins/kubeflow/pytorch/pytorch_grouper_test.go

Currently, if I launch a PyTorchJob with just a "Master" pod, it will fail as a "Worker" pod is a requirement. It should not be a requirement.
It is also possible to launch just "Worker" pods without a "Master" pod (see [this flag](https://docs.run.ai/v2.19/Researcher/cli-reference/runai-submit-dist-pytorch/#-no-master) as an example).
Ultimately I am removing the requirement to have a "Worker" pod: there will be no requirement to have either a "Master" or "Worker" pod.

Remove requirement for Worker when using PyTorchJob

---

pkg/scheduler/actions/allocate/allocate_test.go
pkg/scheduler/cache/cache.go
pkg/scheduler/cache/status_updater/default_status_updater.go
pkg/scheduler/cache/status_updater/interface.go
pkg/scheduler/framework/statement.go

To support clusters with very large scale we want to move the patching of the pod node pool labels to happen concurrently in the background instead of blocking the scheduler loop.

refactor(scheduler): patch pod labels concurrently

---

CHANGELOG.md
pkg/scheduler/actions/common/solvers/pod_scenario_builder.go
pkg/scheduler/actions/common/solvers/pod_scenario_builder_test.go
test/e2e/suites/reclaim/reclaim_elastic_test.go

While going through the solvers, @bugra-gedik-nv noticed a potential bug in pod_scenario_builder, where we jump to the next scenario if any of the potentialVictimTasks are already in recordedVictimTasks.
https://github.com/NVIDIA/KAI-Scheduler/blob/main/pkg/scheduler/actions/common/solvers/pod_scenario_builder.go#L77-L82
When an elastic job is the victim, `GetTasksToEvict` will only return the last task from reverse TaskOrderFn of a victim until the job has equal or less than `MinAvailable` tasks to consider for scenario (the `jobHasMoreTasks = false` situation).
https://github.com/NVIDIA/KAI-Scheduler/blob/main/pkg/scheduler/actions/common/solvers/pod_scenario_builder.go#L71-L82
When you have a reclaimer/preemptor with at least 2 tasks to schedule and no free nodes, we would successfully …

scheduler: bugfix: Make pod_scenario_builder build scenarios for rest of elastic job

---

pkg/scheduler/actions/reclaim/reclaim.go
pkg/scheduler/api/types.go
pkg/scheduler/framework/session.go
pkg/scheduler/framework/session_plugins.go
pkg/scheduler/plugins/proportion/proportion.go

This breaks out the changes from #162 regarding some smaller refactors and eliminating ReclaimerInfo from the plugin API, as RequiredResources is specific to proportion plugin only.
The main concern raised by @romanbaron was that ReclaimerInfo.RequiredResources need to be calculated on un-simulated PodGroupInfo.
From my investigation in https://github.com/NVIDIA/KAI-Scheduler/pull/162#pullrequestreview-2863519568, because podGroupInfo now has a cache for `GetTasksToAllocateInitResource`, RequiredResources will always be based on unsimulated results because it is called before job solver gets its hand on the podgroupinfo, which caches the end result for the rest of the scheduler cycle: https://github.com/NVIDIA/KAI-Scheduler/blob/6a1fc6571af1dcacf9f6baf08bf87717c4fafa56/pkg/scheduler/action …

refactor out reclaimerinfo from API

---

deployments/kai-scheduler/templates/services/binder.yaml
deployments/kai-scheduler/values.yaml

Related to https://github.com/NVIDIA/KAI-Scheduler/issues/47
I didn't find how to enable cdi when installing the chart, and it's required to use kai in gke.

binder cdi flag added

---

hack/run-e2e-kind.sh
pkg/scheduler/cache/status_updater/default_status_updater.go
pkg/scheduler/cache/status_updater/default_status_updater_test.go
pkg/scheduler/plugins/minruntime/minruntime.go
pkg/scheduler/plugins/minruntime/resolver.go
test/e2e/modules/utils/logs.go
test/e2e/suites/reclaim/reclaim_test.go

This fixes the issue introduced in https://github.com/NVIDIA/KAI-Scheduler/commit/ac873ab1c77472d27c181f2b3d21b727274f5cfd that causes LastStartTimestamp and StaleTimestamp to not be patched in when the entire podgroup is scheduled at once. 
Also fixes minruntime using the wrong default value for reclaims, and cleans up the code to be leaner and error less (old code would print errors when default values were not set, which would log errors on every scheduling loop. Now if they arent set we just assume the hardcoded defaults).

Fix default_status_updater so Annotation updates are properly applied

---

pkg/scheduler/cache/status_updater/default_status_updater_test.go

In the TestDefaultStatusUpdater_RecordJobStatusEvent unitest, set the right amout of calls for podGroup update waitGroup

Unitest fix - TestDefaultStatusUpdater_RecordJobStatusEvent

---

pkg/podgroupcontroller/utilities/pod-group/preemptible.go
pkg/podgroupcontroller/utilities/pod-group/preemptible_test.go

When a PodGroup is created with a PriorityClass that doesn't exist the current behavior will just fail the pod group controller from updating the status. We will want it to at least update the resources status if possible and mark the podGroup as preemptible because this is how the scheduler treats it

fix: pod group controller fails on missing priority class

---

go.mod
go.sum
pkg/scheduler/plugins/minruntime/minruntime.go
pkg/scheduler/plugins/minruntime/minruntime_test.go

* using str2duration lib to parse min runtime duration to support more cases - now supporting also "d" (days) and "w" (weeks).
* validating the duration provided is not negative

Fix preempt reclaim minruntime string parsing

---

pkg/podgroupcontroller/controllers/status_updater_test.go
pkg/podgroupcontroller/utilities/pod-group/preemptible.go
pkg/podgroupcontroller/utilities/pod-group/preemptible_test.go

* a small fix in code and tests (was not affecting actual behavior) - priority classes are not namespaced

Fix priorityclass not namespaced

---

pkg/podgroupcontroller/controllers/status_updater_test.go
pkg/podgroupcontroller/utilities/pod-group/preemptible.go
pkg/podgroupcontroller/utilities/pod-group/preemptible_test.go

cherry pick of https://github.com/NVIDIA/KAI-Scheduler/pull/279
* priority classes are not namespaced - little fix

Fix priorityclass not namespaced (#279)

---

pkg/scheduler/cache/cluster_info/cluster_info.go

This PR can partially optimize this [issue](https://github.com/NVIDIA/KAI-Scheduler/issues/315).
After testing, under the same environment (cluster with 4000+ nodes and 140000+ pods), the snapshot analysis time can be reduced from around 2 seconds to around 1 second.

Remove unnecessary deepcopy to optimize performance

---

CHANGELOG.md
pkg/scheduler/actions/allocate/allocateGpuMemory_test.go
pkg/scheduler/api/node_info/gpu_sharing_node_info.go
pkg/scheduler/api/node_info/node_info.go

Fixed a miscalculation where cpu/memory releasing resources were considered idle when requesting GPU fraction/memory

v0.4 cherrypick of https://github.com/NVIDIA/KAI-Scheduler/pull/313 

---

CHANGELOG.md
pkg/scheduler/actions/allocate/allocateGpuMemory_test.go
pkg/scheduler/api/node_info/gpu_sharing_node_info.go
pkg/scheduler/api/node_info/node_info.go

Fixed a miscalculation where cpu/memory releasing resources were considered idle when requesting GPU fraction/memory

v0.6 cherrypick of https://github.com/NVIDIA/KAI-Scheduler/pull/313

---

docs/developer/designs/hierarchical-podgroup/README.md

Grove workload architecture comprises multiple PodCliques, decoupling prefill from decode operations and leader from workers pods, thereby enabling each PodClique to utilize a distinct pod template specification and to scale independently. Upon scheduling a Grove workload, all constituent PodCliques are scheduled as a gang to ensure collective orchestration. Certain PodCliques may prefer or require close location within the cluster to benefit from reduced network latency and faster communication. A simple example is the leaders and workers pods, where, despite belonging to separate PodCliques, these components maintain tight coupling and frequent interactions.
This PR suggest an extension to PodGroup CRD that supports this requirement.

Design doc for hierarchical PodGroup structure

---

docs/gpu-sharing/README.md
pkg/binder/binding/resourcereservation/resource_reservation.go

Fixes - #340 
Reservation pods use the NVML library for GPU discovery, which requires the NVIDIA runtime.
Without explicitly setting RuntimeClassName, pods may fail if the cluster default is not nvidia.
This PR ensures reliable GPU sharing behavior by:

Explicitly set runtimeClassName to `nvidia` for GPU reservation pods

---

pkg/scheduler/api/unschedule_info.go
pkg/scheduler/api/unschedule_info_test.go

A small bug that was discovered in messages outputted by KAI-scheduler in the scenario where a non-preemptible job requests more resources than available.

fix: humanize message and add tests

---

deployments/kai-scheduler/templates/crd-upgrader.yaml

This MR makes the `crd-upgrader` `Job` use the `global.securityContext`, like the other pre-sync hook `Job`s do. This allows deploying the Helm chart in environments where pods not setting certain security contexts fields are rejected.

fix: use global.securityContext in crd-upgrader

---

docs/fairness/README.md
pkg/scheduler/actions/reclaim/reclaimDepartments_test.go
pkg/scheduler/plugins/proportion/proportion.go
pkg/scheduler/plugins/proportion/proportion_test.go
pkg/scheduler/plugins/proportion/reclaimable/reclaimable.go
pkg/scheduler/plugins/proportion/reclaimable/reclaimable_test.go

Currently it is possible for a reclaim to fail between two departments due to a third department requesting quota that it can't receive. To help remediate this issue this PR will allow queues to reclaim from other queues if their utilization ratio (allocation / fair share) is better for all resources.
The original intention for checking that the fair share is not over 1 was to prevent reclaim cycles where the reclaimed project will be able to reclaim the resources back and to create an infinite loop of reclaims and this test is a more relaxed version of this which will also achieve the same goal by always lowering the utilization ratio.
There is an action test for reclaim that show this issue and also unit test in reclaimable_test.go 
This change will allow the scheduler to find more …

Allow reclaiming with lower utilization ratio

---

pkg/scheduler/api/pod_info/pod_info.go
pkg/scheduler/cache/cluster_info/cluster_info_test.go
pkg/scheduler/plugins/proportion/proportion.go
pkg/scheduler/plugins/proportion/proportion_test.go

This PR tries to fix two problems we found:
1. If a MIG pod is not scheduled by Kai, its `ResourceRequestType` is not set to `MigInstance`. This results in incorrect idle resource calculation for the node, which in turn leads to inaccurate scheduling decisions.
2. When calculating resource proportions, the MIG resource of a node is counted twice.

Fix: incorrect scheduling decision and calculation when using MIG

---

pkg/scheduler/actions/integration_tests/allocate/allocate_test.go
pkg/scheduler/actions/integration_tests/allocate/allocate_topology_test.go

Those are the tests I have implemented:
- Require Only
- Require topology level - schedule all tasks on capable domain (even though first domain can have part of the tasks)
- Require topology level on multi hierarchy topology (Rack, Spine) - schedule all tasks on capable domain (even though first domain can have part of the tasks)
- Multi hierarchy topology (Rack, Spine) cluster, require higher level (Rack) - schedule all tasks on capable domain (even though first domain can have part of the tasks)
- Multi hierarchy topology (Rack, Spine) cluster, require higher level (Rack) - schedule all tasks on capable domain (even though its not empty domain)
- Require topology level - dont schedule as no domain is capable to have all tasks
- Prefer Only
- Prefer topology level - schedule all tasks …

Topology scheduling tests

---

deployments/kai-scheduler/templates/rbac/podgrouper.yaml
pkg/podgrouper/podgrouper/hub/hub.go
pkg/podgrouper/podgrouper/plugins/grove/grove_grouper.go

Gove top-level CR `PodGangSet` has been renamed to `PodCliqueSet` ([Grove Issue](https://github.com/NVIDIA/grove/issues/182)). This PR adds support for new name in KAI.

Grove: Add support for PodGangSet to PodCliqueSet API name change

---

go.mod
go.sum
pkg/scheduler/cache/usagedb/api/interface.go
pkg/scheduler/cache/usagedb/prometheus/prometheus.go
pkg/scheduler/cache/usagedb/prometheus/prometheus_test.go

Add support for Prometheus client tumbling window configuration - allow the usage data used for fairshare calculations to be reset each X time instead of a sliding window

Time fairshare - support tumbling window config

---

cmd/binder/app/options.go
cmd/binder/main.go
cmd/podgroupcontroller/app/app.go
cmd/podgroupcontroller/app/options.go
cmd/podgroupcontroller/main.go
pkg/binder/controllers/bindrequest_controller.go
pkg/binder/controllers/pod_controller.go
pkg/env-tests/binder/binder.go
pkg/env-tests/podgroupcontroller/podgroupcontroller.go
pkg/env-tests/podgroupcontroller_test.go
pkg/env-tests/scheduler_test.go

Added the infra to test the podgroupcontroller in env-tests. Added one sanity test as example.

Pod-group-controller env tests

---

docs/metrics/service-monitors.yaml
pkg/scheduler/cache/usagedb/prometheus/prometheus.go
pkg/scheduler/conf_util/scheduler_conf_util.go

This PR normalizes the historical resource usage for each queue to the cluster capacity at the relevant time duration in the prometheus client plugin.

TAS: Normalize usage to cluster capacity in prometheus

---

cmd/scheduler/app/server.go
pkg/env-tests/binder/binder.go
pkg/env-tests/env_tests_suite_test.go
pkg/env-tests/scheduler/scheduler.go
pkg/env-tests/scheduler_test.go
pkg/scheduler/cache/cache.go
pkg/scheduler/cache/usagedb/api/defaults.go
pkg/scheduler/cache/usagedb/api/interface.go
pkg/scheduler/conf_util/scheduler_conf_util.go
pkg/scheduler/scheduler.go

* Init default actions & plugins outside the scheduler, to allow injecting scheduler config externally
* Changed binder metrics port in env tests
* Allow configuration of informer params from UsageDB params (fetch interval, staleness period, timeout)

Prepare infra for time aware env tests
